### ISSUE TITLE
Deprecation warning - ensureIndex is deprecated.

### ISSUE THREAD

**Issue by sapcik** [node-casbin/mongoose-adapter#51]
Hi,

I'm getting following warning:

> (node:42970) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
    at NativeCollection.<computed> [as ensureIndex] (/project/node_modules/casbin-mongoose-adapter/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:244:33)
    at NativeCollection.create (/project/node_modules/casbin-mongoose-adapter/node_modules/mongoose/lib/model.js:1753:33)

Here is a list of libraries that I'm using:

1. casbin: "^5.11.5",
2. casbin-mongoose-adapter: "^3.1.1",
3. mongoose: "^6.0.12",

Please, can it be upgraded to work with a newer version of mongoose/mongo? 

As far as I understand, string `ensureIndex` should be replaced by `createIndexes` in `lib/model.js` 

Thanks,
Wojciech

**Comment by hsluoyz** [comment]
@fabian4

**Comment by hsluoyz** [comment]
@sapcik released: https://github.com/node-casbin/mongoose-adapter/releases/tag/v4.0.0

**Comment by sapcik** [comment]
Awesome, thank you!
